<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ClientParticulier;

class ClientParticulierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $types = ['Prospect', 'Client'];
        $categories = ['Premium', 'Direct', 'Revendeur'];
        $villes = ['Casablanca', "Rabat", "Tanger", "Safi", "Tetouan", "Nador", "Ouarzazat"];

        $clients = [
            [
                'CodeClient' => 'C001',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJKZ',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '123 Rue Example, Casablanca',
                'type_client' => $types[1],
                'categorie' => $categories[0],
                'tele' => '0612345678',
                'ville' => $villes[0],
                'mod_id' => 1,
                'abreviation' => 'CA',
                'code_postal' => '20000',
                "montant_plafond" => 1000,
                "secteur_id" => 1,
                "seince" => 20,
                'user_id' => 1,
                'zone_id' => 1,
                'region_id' => 1,
            ],
            [
                'CodeClient' => 'C002',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJKZZ',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '456 Rue Example, Rabat',
                'type_client' => $types[0],
                "secteur_id" => 1,
                'categorie' => $categories[1],
                'tele' => '0623456789',
                'ville' => $villes[1],
                'abreviation' => 'RB',
                'mod_id' => 1,
                "montant_plafond" => 1100,
                "seince" => 40,
                'code_postal' => '10000',
                'user_id' => 1,
                'zone_id' => 2,
                'region_id' => 2,
            ],
            [
                'CodeClient' => 'C003',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJK3E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                "secteur_id" => 2,
                'adresse' => '789 Rue Example, Marrakech',
                'type_client' => $types[1],
                'categorie' => $categories[2],
                'tele' => '0634567890',
                'ville' => $villes[3],
                "seince" => 20,
                "montant_plafond" => 2000,
                'mod_id' => 1,
                'abreviation' => 'MC',
                'code_postal' => '40000',
                'user_id' => 1,
                'zone_id' => 3,
                'region_id' => 3,
            ],
            [
                'CodeClient' => 'C004',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJ2K3E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '321 Rue Example, Fes',
                'type_client' => $types[0],
                'categorie' => $categories[0],
                'tele' => '0645678901',
                "seince" => 20,
                'ville' => $villes[4],
                "secteur_id" => 2,
                "montant_plafond" => 3000,
                'mod_id' => 1,
                'abreviation' => 'FD',
                'code_postal' => '30000',
                'user_id' => 1,
                'zone_id' => 4,
                'region_id' => 4,
            ],
            [
                'CodeClient' => 'C005',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJK2143E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '654 Rue Example, Agadir',
                'type_client' => $types[1],
                'categorie' => $categories[1],
                "secteur_id" => 2,
                'tele' => '0656789012',
                "montant_plafond" => 1100,
                "seince" => 60,
                'ville' => $villes[3],
                'abreviation' => 'AE',
                'mod_id' => 1,
                'code_postal' => '80000',
                'user_id' => 1,
                'zone_id' => 5,
                'region_id' => 5,
            ],
            [
                'CodeClient' => 'C006',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJK213E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '987 Rue Example, Tanger',
                'type_client' => $types[0],
                'categorie' => $categories[2],
                "secteur_id" => 2,
                'tele' => '0667890123',
                'ville' => $villes[3],
                'mod_id' => 1,
                "seince" => 20,
                "montant_plafond" => 1100,
                'abreviation' => 'TF',
                'code_postal' => '90000',
                'user_id' => 1,
                'zone_id' => 6,
                'region_id' => 6,
            ],
            [
                'CodeClient' => 'C007',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BE12JK3E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '135 Rue Example, Oujda',
                'type_client' => $types[1],
                "secteur_id" => 1,
                'categorie' => $categories[0],
                'tele' => '0678901234',
                'ville' => $villes[2],
                "seince" => 40,
                'mod_id' => 2,
                'abreviation' => 'OG',
                "montant_plafond" => 1100,
                'code_postal' => '60000',
                'user_id' => 1,
                'zone_id' => 7,
                'region_id' => 7,
            ],
            [
                'CodeClient' => 'C008',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BE291K3E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '246 Rue Example, Kenitra',
                'type_client' => $types[0],
                "secteur_id" => 1,
                'categorie' => $categories[1],
                'tele' => '0689012345',
                'ville' => $villes[1],
                'abreviation' => 'KH',
                "seince" => 40,
                "montant_plafond" => 1100,
                'code_postal' => '14000',
                'user_id' => 1,
                'mod_id' => 2,
                'zone_id' => 8,
                'region_id' => 8,
            ],
            [
                'CodeClient' => 'C009',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BED1453E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '357 Rue Example, Settat',
                'type_client' => $types[1],
                'categorie' => $categories[2],
                'tele' => '0690123456',
                'ville' => $villes[0],
                "montant_plafond" => 1100,
                "secteur_id" => 1,
                'abreviation' => 'SI',
                "seince" => 20,
                'code_postal' => '26000',
                'mod_id' => 2,
                'user_id' => 1,
                'zone_id' => 9,
                'region_id' => 9,
            ],
            [
                'CodeClient' => 'C010',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BE290K3E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '468 Rue Example, Safi',
                'type_client' => $types[0],
                'categorie' => $categories[0],
                'tele' => '0701234567',
                'ville' => $villes[0],
                "montant_plafond" => 1100,
                'abreviation' => 'SJ',
                'code_postal' => '46000',
                "seince" => 20,
                'mod_id' => 1,
                "secteur_id" => 1,
                'user_id' => 1,
                'zone_id' => 10,
                'region_id' => 10,
            ],
        ];

        foreach ($clients as $client) {
            ClientParticulier::create($client);
        }
    }
}
